version: 2

sources:
 - name: src 
   database: ODS
   schema: land

   tables:
    - name: SOURCE_CLAIMS
      identifier: SOURCE_CLAIMS

models:
 - name:  t_claim_src
   data_tests:
    - no_duplicate_row
    - duplicate_comb_check:
        arguments: 
          col1: claim_id
          col2: policy_id
    - all_not_null
    - dynamic_unique_col:
        arguments:
          columns:
          - claim_id
          - policy_id
          - claim_amount

   columns:
    - name:   claim_amount
      data_tests: 
          - positive_val
    - name:   created_at
      data_tests:
          - no_future_date
    - name: created_at
      data_tests:
          - updated_after_created:
              arguments:
                compare_column: changed_at
    - name: claim_id    
      data_tests:
          - not_null
          - unique
    - name: claim_status
      data_tests:
          - accepted_values:
              arguments:
                values: ['OPEN','CLOSED']
    - name: claim_status 
      data_tests:
        - no_blank_space 
    - name: claim_status 
      data_tests: 
        - reject_claim_amt: 
            arguments:
              stat_column: claim_status
              amt_column: claim_amount
        - case_insensistive_status:
            arguments:
              values: ['open',' closed']